"""Slack Block Kit message builder for news articles."""

from __future__ import annotations

from datetime import date
from urllib.parse import urlparse

from news_collector.models import Article, Translation

# Tag-based severity emoji
_TAG_EMOJI: dict[str, str] = {
    "data-breach": "🔴",
    "ransomware": "🔴",
    "zero-day": "🔴",
    "phishing": "🔴",
    "malware": "🔴",
    "vulnerability": "🟠",
    "cve": "🟠",
    "policy": "🟢",
    "regulation": "🟢",
    "education": "🟢",
    "government": "🔵",
    "cloud-security": "🔵",
    "ai-security": "🟣",
}
_DEFAULT_EMOJI = "⚪"


def _pick_emoji(tags: list[str]) -> str:
    """Pick a severity emoji based on article tags."""
    for tag in tags:
        if tag in _TAG_EMOJI:
            return _TAG_EMOJI[tag]
    return _DEFAULT_EMOJI


def build_digest_blocks(
    articles: list[Article],
    *,
    title: str = "News Digest",
    lang: str = "",
    commentaries: dict[str, str] | None = None,
) -> list[dict]:
    """Build a single Slack Block Kit message containing all articles.

    Output is a blocks array for use with `swrite post --format blocks --no-unfurl`.
    """
    if not articles:
        return []

    blocks: list[dict] = []

    # ── Header ──
    blocks.append({
        "type": "header",
        "text": {"type": "plain_text", "text": f"📡 {title}", "emoji": True},
    })

    genres = sorted(set(a.genre for a in articles))
    genre_text = " · ".join(genres)
    blocks.append({
        "type": "context",
        "elements": [{
            "type": "mrkdwn",
            "text": f"*{len(articles)}* articles  ｜  {genre_text}  ｜  {date.today().isoformat()}",
        }],
    })
    blocks.append({"type": "divider"})

    # ── Articles ──
    for i, article in enumerate(articles):
        commentary = commentaries.get(article.id) if commentaries else None
        _append_article_blocks(blocks, article, lang=lang, commentary=commentary)
        if i < len(articles) - 1:
            blocks.append({"type": "divider"})

    # ── Footer ──
    blocks.append({"type": "divider"})
    blocks.append({
        "type": "context",
        "elements": [{
            "type": "mrkdwn",
            "text": "_Generated by news-collector_",
        }],
    })

    return blocks


def _append_article_blocks(
    blocks: list[dict],
    article: Article,
    *,
    lang: str = "",
    commentary: str | None = None,
) -> None:
    """Append Block Kit blocks for a single article."""

    trans: Translation | None = article.translations.get(lang) if lang else None
    emoji = _pick_emoji(article.tags)

    # Title with severity emoji + link
    title_text = f"{emoji}  *<{article.url}|{_escape(article.title)}>*"
    if trans:
        title_text += f"\n{_escape(trans.title)}"

    blocks.append({
        "type": "section",
        "text": {"type": "mrkdwn", "text": title_text},
    })

    # Summary
    if trans:
        summary = trans.summary
    elif article.summary:
        summary = article.summary
    else:
        summary = article.summary_raw[:300]

    if summary:
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": _escape(summary)},
        })

    # Curator commentary
    if commentary:
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"> 💬  {_escape(commentary)}",
            },
        })

    # Metadata: source, date, tags
    meta_parts: list[str] = []
    meta_parts.append(f"📰  {_escape(article.source)}")
    if article.published_date:
        meta_parts.append(f"📅  {article.published_date.isoformat()}")
    meta_text = "  ｜  ".join(meta_parts)

    meta_elements: list[dict] = [{"type": "mrkdwn", "text": meta_text}]

    if article.tags:
        tag_text = "  ".join(f"`{t}`" for t in article.tags[:8])
        meta_elements.append({"type": "mrkdwn", "text": tag_text})

    blocks.append({"type": "context", "elements": meta_elements})

    # Source URL (always visible)
    blocks.append({
        "type": "context",
        "elements": [{
            "type": "mrkdwn",
            "text": f"🔗  {article.url}",
        }],
    })


def _escape(text: str) -> str:
    """Escape special Slack mrkdwn characters in user-supplied text."""
    return (
        text
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )
