"""Slack Block Kit message builder for news articles."""

from __future__ import annotations

from datetime import date
from urllib.parse import urlparse

from news_collector.models import Article, Translation


def build_digest_blocks(
    articles: list[Article],
    *,
    title: str = "News Digest",
    lang: str = "",
    commentaries: dict[str, str] | None = None,
) -> list[dict]:
    """Build a Slack Block Kit message for a list of articles.

    Args:
        articles: Articles to include.
        title: Digest title for the header.
        lang: If set, use translated title/summary for this language.
        commentaries: Optional mapping of article_id → curator commentary.

    Returns:
        A list of Block Kit blocks (ready for swrite --format blocks).
    """
    if not articles:
        return []

    blocks: list[dict] = []

    # ── Header ──
    blocks.append({
        "type": "header",
        "text": {"type": "plain_text", "text": f"📡 {title}", "emoji": True},
    })

    # Subtitle with stats
    genres = sorted(set(a.genre for a in articles))
    genre_text = " · ".join(genres)
    blocks.append({
        "type": "context",
        "elements": [{
            "type": "mrkdwn",
            "text": f"*{len(articles)}* articles  ｜  {genre_text}",
        }],
    })
    blocks.append({"type": "divider"})

    # ── Articles ──
    for i, article in enumerate(articles):
        _append_article_blocks(
            blocks, article,
            lang=lang,
            commentary=commentaries.get(article.id) if commentaries else None,
        )
        # Divider between articles (not after last)
        if i < len(articles) - 1:
            blocks.append({"type": "divider"})

    # ── Footer ──
    blocks.append({"type": "divider"})
    blocks.append({
        "type": "context",
        "elements": [{
            "type": "mrkdwn",
            "text": (
                f"_Generated by news-collector_  ｜  "
                f"{date.today().isoformat()}"
            ),
        }],
    })

    return blocks


def _append_article_blocks(
    blocks: list[dict],
    article: Article,
    *,
    lang: str = "",
    commentary: str | None = None,
) -> None:
    """Append Block Kit blocks for a single article."""

    trans: Translation | None = article.translations.get(lang) if lang else None

    # Title (original, linked) + translated subtitle
    title_text = f"*<{article.url}|{_escape(article.title)}>*"
    if trans:
        title_text += f"\n{_escape(trans.title)}"

    blocks.append({
        "type": "section",
        "text": {"type": "mrkdwn", "text": title_text},
    })

    # Summary
    if trans:
        summary = trans.summary
    elif article.summary:
        summary = article.summary
    else:
        summary = article.summary_raw[:300]

    if summary:
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": _escape(summary)},
        })

    # Curator commentary
    if commentary:
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"> 💬  {_escape(commentary)}",
            },
        })

    # Metadata row: source, date, tags
    meta_parts: list[str] = []
    meta_parts.append(f"📰  {_escape(article.source)}")
    if article.published_date:
        meta_parts.append(f"📅  {article.published_date.isoformat()}")
    meta_text = "  ｜  ".join(meta_parts)

    meta_elements: list[dict] = [{"type": "mrkdwn", "text": meta_text}]

    if article.tags:
        tag_text = "  ".join(f"`{t}`" for t in article.tags[:8])
        meta_elements.append({"type": "mrkdwn", "text": tag_text})

    blocks.append({"type": "context", "elements": meta_elements})

    # Source URL (always visible)
    domain = urlparse(article.url).netloc if article.url else ""
    blocks.append({
        "type": "context",
        "elements": [{
            "type": "mrkdwn",
            "text": f"🔗  {article.url}",
        }],
    })


def _escape(text: str) -> str:
    """Escape special Slack mrkdwn characters in user-supplied text."""
    return (
        text
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )
